// Package provider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package provider

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+KxhcZppc9W7XafSl49hpo9R2fI7dTi/xeSByKSEBAQQAbTE+/fcbACRF",
	"ipCtdFInM9dvFgnsLha7zz679C2ORCoFB240Ht9iSRRJwYByv06VuKYxqEl8SszcPolBR4pKQwXHY3zB",
	"6ccMEI2BG5pQUEgkyMwByWIj7mBYkFQywGM8HO3A7g97T7vw47NpdziKd7pk94e97u5ob2+4O3y6OxgM",
	"cAdTK1lafR3MSWp3ysoO3MEKPmZUQYzHRmXQwTqaQ0qscSlZHAGfWUv3djo4pbz8OexYiQaUlf2ft6T7",
	"adB9dvm4+KN7eTvo7A2X5fMnPz3CHWxyaXVroyif4eVyWapyrnmhlFBtj5z9fICe/jh4iqxbGSXcILAr",
	"kQItBdeAO/Y0EpShoP1+QyhrS3qZpYR3FZCYTBkgWEhGOLEvkZYQ0YRGyAhk5lQjEUWZUsAjaDj8fA7o",
	"O+vC71BCgcWIalR6D00zg26IRlyY8rri9qntdWhDrOT27Z9NkIIEnGKUCOWNqazzB99gW9+91f0tgyIR",
	"KiUGj3GmaLdSGrJXG2IyHfDn+fkp8i9RJOKGNbuDQSWJcgMzUFaUoYYFzv1mLpRB8+b96CxNicprCTBl",
	"kDaOPOHXhNEYTbjMTMh0/+BuNxe5llM+c4q8k93Ouq65MVKP+/04SnvF014k0tLr1JvSpYUp27p3WU+/",
	"t7hQ6/10Wa0W0/cQGXuil0BYCDj88/I6NOUzBkZwmyUiU1E7S2QQfw4IF5xGhCH7vvR9TUjNId4Saz+J",
	"X3OWl/CxfQDVbQ7IzoPuarqkgxddArJbmeiPZoFJW4cWVl52sGSZIqwSbhVWbqqQj/JZxoiqH6+0ANQ1",
	"jaAEzp6NAyr6xTJrWInt7YP+nDFWIXjlTaRAKtDAjQOh1g1FCoiBK0PTQAyf0xS0IalEN3PgjRLhQCih",
	"ShukYEa1AeWAqArJmBjoOrFbXF5MtWQkv/KF4x5MLRYju7jArw2l69dsCr9RZdAb71d0ulrVsgF4LAXl",
	"ZoNny9fo4uzIukNB0x/7pxML1CSKQGs6ZeHE1nLYSGwiaf96SJick2H/Ol3L6ZCZPhautgr3O+u69We+",
	"zeXQeBsKUV5EwNWfzSW+LCO494ApGBIT48jIIwUJHuN/9FcEq1/wh355pONy/bKkOhvc4yK0uIM7/fIh",
	"m8I1VaY7HO2ELt1mrMvfwI0fUW2sktUapDMphTIQ18p7oX695LwtEAB3cAwM3B+ZtMlr4YwaSJ3KDUUP",
	"E6VIbn+Hkf6sRCEH9KtoaRy+jM6tWcX9tcBd2NU1KO3saFEB9x4V78sbqrvIX9lp6clm4SgTFjeC8fqt",
	"DbnvH7t3/52CIU9+co/++ShIeLy2qzB7OLc2iGRlk73DCmtEkliq37ApDSnxN/kn0Z0RbZCX8GeRfY14",
	"uGSpIe2aF1oXd/m5hXgVSrfln1c0XjYqc7UGN0qxbJeGcDGuFtbLsU3CtodPyYxy6z7EiiStK28WYg4L",
	"cyXJDK6M+ACBoD23j11CKzCKwnXJJe1OZHdaBQp0xtbiFfJX8t8Hk73J+xf58ehicHL+x87R7xe7r3+f",
	"mOPzVx+O8+H85PBidHT+r/zk/R+Lk8MXOyeH+zfHB6+ehaJqdYjx7QoitkHONnIsA/SzhbPjW0zimFpH",
	"EHZac5sPuqaf9quVqAR2RKYiM+ulsOl/y2IEv3I9Rsv3v4CYKSLnNEJ+netFQjTAozA0LyDTXSDadIch",
	"b5axfK8TSzA9IJJE1OR3sd4D17yZVVEgbBtOsJESd/AnwQOO2b8mlJEpZdTkyC5BQiHr8gi4AbUJ8lcr",
	"utMt+Peyg1uH31xromIJotxjVoj3GmEIu4pkFko0Qxg6OL1AkVCgEfFnbDK60Ybe04lNIRUq3yTZvw2L",
	"xcPz58Ee08nlweD0UnmWTv0kx65qxN/wLlu1EYrMNootXm+wdhSytn19SzeQSIRrOAQ3JLJguVzP3MOD",
	"4xZNcry6i85cj+FDGREeo5RwMoPUxXjS2qV77/i5LZmOlVtj7UodJGJF/1LITpi4QUSjGBLKIUbUFcZ3",
	"3NoGfE545JXaaBKasN47G1uMRsC1c2Ix+9qXJJoDGvUsYckUq/UANzc3PeJe94Sa9Yu9un80OXhx8uZF",
	"d9Qb9OYmZbVZBg65BXdwxXBWnMSzRU4kxWO80xv0dj1NmbuwL1vJ8S2egdnYPkRziD64WrPpTnCNlE5i",
	"B5Hm5apZ91Mzp3I0GJT3Dr67IlIyGrmt/ffaE7TVOPAuCHxZNsKt2Hn9qwu8Yp6zdhIbo2TWaNXt4n6j",
	"kAX9cQYmU1wjUlXwVbdbkbNKDLqhZo6ELAA3ocyAy4l1Z1m6cFqnArX57dtW++nE1LRM83U674avHzNQ",
	"+Wr62qBUAQ6/7KwrOiYLmmZpDUoKNoGk1W9RIqwqJQtPXTT91NQZQ0IyZgoMSr2C8hflxa82OrWNW9Ef",
	"6VmVR/WQOTUWddf5L//CQG3wwkC4vsncnCDJ2KpE29TdvdOGYjz5/efZ4mfeASOek9gNlkG7Elvd1UPp",
	"v+CwkBBZfgzFmnoGu8aW1IZaupbHFX25tIRU6GDu+kxFBHG4aWWrZSq+u0GEI1hQbSyjFhx673ij3lBt",
	"eUwqhfXJ+B3voknie/tYgB/Fu+2dQtObUwTcqNxu9N11XN/k1hZYoUkKfS4qoyaHHT8fLvcX/dem/TFN",
	"3NTXNCQ0KxqhTKPHkeAJo5F5Uohard8g0Oq6V1QL2Q7ceWtDjjuh7XUJldWlTA5djq/83bBgQ8LTGD/c",
	"B6VL39OCNs9FnH9xxPCJ0vxatnwApAolaFXwiyhEjxV06/fxxOLGaDB8WGuKnEKPbbK1zHlQCC0/Dvkv",
	"Mk77s4fTflAkIuoWo0ZVT2vC3IjXUthMgzNuNHo4436zjvG4AYsIZFnivrUyUysToc8E7XrTYI6rQdMk",
	"Xvoa5KaogWqUimtApF2HEiXS4guYC+W8BaqHTuZmUA25ZbWkv/b/AAHisxuYXZXm+QPFSFeUheVfLc8m",
	"h24kyyjE3obdh7Oh8ogt+InIePwthrOPlVqc3R3MnXDf8wuYUKhOc0SNRpn/vDE5DHWBf2GYPkzV+ya4",
	"+d8Bv23A+1CV90S5Lc/tz3Rt+r8e8m6QBPWySotPJcTMUZppg1JionlDSG1zK0P2pWT5l82R/1My+k0U",
	"pBrx++qZ+VW5Z5Nt2kpBuDDz2uDqWwSPEgG2pX7Fh9syW/1gt/FfHC4ni62t787rg9T6FHv1ib/1D5S4",
	"PQ5rDGpDe8v/Gbpc/i8AAP//YBeXRy0qAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
