// Package provider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package provider

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+KxhcZppc9W7XafSl49hpo9R2fI7dTi/xeSByKSEBAQQAbTE+/fcbACRF",
	"ipCtdFInM9dvFgnsLha7zz679C2ORCoFB240Ht9iSRRJwYByv06VuKYxqEl8SszcPolBR4pKQwXHY3zB",
	"6ccMEI2BG5pQUEgkyMwByWIj7mBYkFQywGM8HO3A7g97T7vw47NpdziKd7pk94e97u5ob2+4O3y6OxgM",
	"cAdTK1lafR3MSWp3ysoO3MEKPmZUQYzHRmXQwTqaQ0qscSlZHAGfWUv3djo4pbz8OexYiQaUlf2ft6T7",
	"adB9dvm4+KN7eTvo7A2X5fMnPz3CHWxyaXVroyif4eVyWapyrnmhlFBtj5z9fICe/jh4iqxbGSXcILAr",
	"kQItBdeAO/Y0EpShoP1+QyhrS3qZpYR3FZCYTBkgWEhGOLEvkZYQ0YRGyAhk5lQjEUWZUsAjaDj8fA7o",
	"O+vC71BCgcWIalR6D00zg26IRlyY8rri9qntdWhDrOT27Z9NkIIEnGKUCOWNqazzB99gW9+91f0tgyIR",
	"KiUGj3GmaLdSGrJXG2IyHfDn+fkp8i9RJOKGNbuDQSWJcgMzUFaUoYYFzv1mLpRB8+b96CxNicprCTBl",
	"kDaOPOHXhNEYTbjMTMh0/+BuNxe5llM+c4q8k93Ouq65MVKP+/04SnvF014k0tLr1JvSpYUp27p3WU+/",
	"t7hQ6/10Wa0W0/cQGXuil0BYCDj88/I6NOUzBkZwmyUiU1E7S2QQfw4IF5xGhCH7vvR9TUjNId4Saz+J",
	"X3OWl/CxfQDVbQ7IzoPuarqkgxddArJbmeiPZoFJW4cWVl52sGSZIqwSbhVWbqqQj/JZxoiqH6+0ANQ1",
	"jaAEzp6NAyr6xTJrWInt7YP+nDFWIXjlTaRAKtDAjQOh1g1FCoiBK0PTQAyf0xS0IalEN3PgjRLhQCih",
	"ShukYEa1AeWAqArJmBjoOrFbXF5MtWQkv/KF4x5MLRYju7jArw2l69dsCr9RZdAb71d0ulrVsgF4LAXl",
	"ZoNny9fo4uzIukNB0x/7pxML1CSKQGs6ZeHE1nLYSGwiaf96SJick2H/Ol3L6ZCZPhautgr3O+u69We+",
	"zeXQeBsKUV5EwNWfzSW+LCO494ApGBIT48jIIwUJHuN/9FcEq1/wh355pONy/bKkOhvc4yK0uIM7/fIh",
	"m8I1VaY7HO2ELt1mrMvfwI0fUW2sktUapDMphTIQ18p7oX695LwtEAB3cAwM3B+ZtMlr4YwaSJ3KDUUP",
	"E6VIbn+Hkf6sRCEH9KtoaRy+jM6tWcX9tcBd2NU1KO3saFEB9x4V78sbqrvIX9lp6clm4SgTFjeC8fqt",
	"DbnvH7t3/52CIU9+co/++ShIeLy2qzB7OLc2iGRlk73DCmtEkliq37ApDSnxN/kn0Z0RbZCX8GeRfY14",
	"uGSpIe2aF1oXd/m5hXgVSrfln1c0XjYqc7UGN0qxbJeGcDGuFtbLsU3CtodPyYxy6z7EiiStK28WYg4L",
	"cyXJDK6M+ACBoD23j11CKzCKwnXJJe1OZHdaBQp0xtbiFfJX8t8Hk73J+xf58ehicHL+x87R7xe7r3+f",
	"mOPzVx+O8+H85PBidHT+r/zk/R+Lk8MXOyeH+zfHB6+ehaKq1DG+XQHENrjZxo1lgHy2UHZ8i0kcU+sG",
	"wk5rTvMh1/TSfrUSlbCOyFRkZr0QNr1vOYzgV67DaHn+FxAzReScRsivc51IiAR4DIam+zPdBaJNd7jB",
	"ly6S73ViCaUHRJKImvwuznvgWjezKgmEbcMINhLiDv4keMAx+9eEMjKljJoc2SVIKGRdHgE3oDYB/mpF",
	"d7oF+152cOvwmytNVCxBlHvECrFeIwxhV5HMQmlmCEMHpxcoEgo0Iv6MTT432tB5OrEppELlmyT7t2Gx",
	"eHj+PNhhOrk8GJxeKs/SqZ/j2FWN+BveZas2QpHZRrHF6w3WjkLWtq9v6cYRiXDthuCGRBYql+uZe3hw",
	"3CJJjlV30ZnrMHwoI8JjlBJOZpC6GE9au3TvHT+3BdNxcmusXamDNKzoXgrZCRM3iGgUQ0I5xIi6sviO",
	"W9uAzwmPvFIbTUIT1ntnY4vRCLh2TiwmX/uSRHNAo56lK5litQ7g5uamR9zrnlCzfrFX948mBy9O3rzo",
	"jnqD3tykrDbJwCG34A6u+M2KkXiuyImkeIx3eoPericpcxf2ZSM5vsUzMBubh2gO0QdXaTbdCa5R0kns",
	"INK8XLXqfmbmVI4Gg/LewfdWREpGI7e1/157erYaBt4FgS/LNrgVO69/dYFXTHPWTmJjlMwajbpd3F/V",
	"4k3+OAOTKa4Rqer3qtetqFklBt1QM0dCFoCbUGbA5cS6syxZOK0Tgdr09m2r+XRialqm+TqZd6PXjxmo",
	"fDV7bRCqAINfdtYVHZMFTbO0BiVFnUfS6rcoEVaVkoUnLpp+auqMISEZMwUGpV5B+Yvy4lcbndrGrciP",
	"9JzKo3rInBqHuuv8l39hoDZYYSBc32RuSpBkbFWiberu3mlDMZz8/vNs8RPvgBHPSezGyqBdia3u6qH0",
	"X3BYSIgsO4ZiTT2DXVtLaiMtXcvjir5c2tZT6GDu+kxFBHG4aWWrZSq+t0GEI1hQbSyfFhx673ij3lBt",
	"eUwqhfXJ+B3vokniO/tYgB/Eu+2dQtObUwTcqNxu9L11XN/k1hZYoUkKfS4qoyaHHT8dLvcX3dem/TFN",
	"3MzXNCQ0KxqhTKPHkeAJo5F5Uohard8g0Oq6V1QL2Q7ceWsjjjuh7XUJldWlTA5djq/83bBgQ8LTGD/c",
	"56RL39GCNs9FnH9xxPCJ0vxWtnwApAolaFXwiyhEjxV06/fxxOLGaDB8WGuKnEKPbbK1zHlQCC0/Dfnv",
	"MU77s4fTflAkIuoWg0ZVT2vC3IDXUthMgzNuNHo4436zjvG4AYsIZFnivrUyUysToY8E7XrTYI6rMdMk",
	"Xvoa5GaogWqUimtApF2HEiXS4vuXC+W8BaqHTuZmUA25ZbWkv/bfAAHisxuYXJXm+QPFSFeUheVfLc8m",
	"h24gyyjE3obdh7Oh8ogt+InIePwthrOPlVqc3R3MnXDf8wuYUKhOc0SNRpn/uDE5DHWBf2GYPkzV+ya4",
	"+d8Bv23A+1CV90S5Lc/tj3Rt+r8e8m6QBPWySosPJcTMUZppg1JionlDSG1zK0P2pWT5l82R/1My+k0U",
	"pBrx++qZ+VW5Z5Nt2kpBuDDz2uDqWwSPEgG2pX7FZ9syW/1gt/E/HC4ni62tr87rg9T6FHv1gb/175O4",
	"PQ5rDGpDe8v/GLpc/i8AAP//RfOQqSsqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
