// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProviderType.
const (
	Container      ProviderType = "container"
	Database       ProviderType = "database"
	VirtualMachine ProviderType = "virtual_machine"
)

// CatalogView defines model for CatalogView.
type CatalogView struct {
	CatalogItems *[]struct {
		AvailableProviders *[]string `json:"available_providers,omitempty"`
		DisplayName        *string   `json:"display_name,omitempty"`
		Name               *string   `json:"name,omitempty"`
		ResourceKind       *string   `json:"resource_kind,omitempty"`
	} `json:"catalog_items,omitempty"`

	// Total Total number of catalog items
	Total *int `json:"total,omitempty"`
}

// Error400 defines model for Error400.
type Error400 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Invalid input
	Error string `json:"error"`
}

// Error404 defines model for Error404.
type Error404 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Resource not found
	Error string `json:"error"`
}

// Error500 defines model for Error500.
type Error500 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Internal service error
	Error string `json:"error"`
}

// Provider defines model for Provider.
type Provider struct {
	// ApiHost Host URL for the provider API
	ApiHost string `json:"apiHost"`

	// Description Summary of Service Provider
	Description string `json:"description"`

	// Endpoint Endpoint of the Service Provider
	Endpoint string `json:"endpoint"`

	// Id Unique identifier for the Service Provider
	Id string `json:"id"`

	// Name Name of the Service Provider
	Name string `json:"name"`

	// Operations Operations performed on the provider endpoint
	Operations []string `json:"operations"`

	// Type Type of the Service Provider
	Type ProviderType `json:"type"`
}

// ProviderType Type of the Service Provider
type ProviderType string

// ProviderList defines model for ProviderList.
type ProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Providers     *[]Provider `json:"providers,omitempty"`
}

// ProviderMetadata defines model for ProviderMetadata.
type ProviderMetadata struct {
	// Labels Custom labels
	Labels *map[string]string `json:"labels,omitempty"`

	// Region Deployment region
	Region string `json:"region"`

	// ResourceConstraints Resource constraints
	ResourceConstraints *map[string]string `json:"resource_constraints,omitempty"`

	// Zone Deployment zone
	Zone string `json:"zone"`
}

// RegisteredProvider defines model for RegisteredProvider.
type RegisteredProvider struct {
	// CatalogItem Associated catalog item
	CatalogItem *string `json:"catalog_item,omitempty"`

	// Endpoint Provider endpoint
	Endpoint *string           `json:"endpoint,omitempty"`
	Metadata *ProviderMetadata `json:"metadata,omitempty"`

	// Operations Supported operations
	Operations *[]string `json:"operations,omitempty"`

	// RegisteredAt Registration timestamp
	RegisteredAt *time.Time `json:"registered_at,omitempty"`

	// ResourceKind Resource type
	ResourceKind *string `json:"resource_kind,omitempty"`

	// ServiceId Service identifier
	ServiceId *string `json:"service_id,omitempty"`

	// Status Provider status
	Status *string `json:"status,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	// Endpoint Provider endpoint URL
	Endpoint string           `json:"endpoint"`
	Metadata ProviderMetadata `json:"metadata"`

	// Operations Supported operations
	Operations []string `json:"operations"`

	// ServiceId Unique service identifier (UUID)
	ServiceId string `json:"service_id"`
}

// RegistrationResponse defines model for RegistrationResponse.
type RegistrationResponse struct {
	// Message Status message
	Message *string `json:"message,omitempty"`

	// RegisteredAt Registration timestamp
	RegisteredAt *time.Time `json:"registered_at,omitempty"`

	// ResourceKind Resource type
	ResourceKind *string `json:"resource_kind,omitempty"`

	// ServiceId Service identifier
	ServiceId *string `json:"service_id,omitempty"`

	// Status Registration status
	Status *string `json:"status,omitempty"`
}

// RegistryView defines model for RegistryView.
type RegistryView struct {
	Providers *[]struct {
		Metadata      *ProviderMetadata `json:"metadata,omitempty"`
		RegisteredAt  *time.Time        `json:"registered_at,omitempty"`
		Registrations *[]struct {
			CatalogItem  *string    `json:"catalog_item,omitempty"`
			Endpoint     *string    `json:"endpoint,omitempty"`
			Operations   *[]string  `json:"operations,omitempty"`
			RegisteredAt *time.Time `json:"registered_at,omitempty"`
			ResourceKind *string    `json:"resource_kind,omitempty"`
		} `json:"registrations,omitempty"`
		ServiceId *string `json:"service_id,omitempty"`
		Status    *string `json:"status,omitempty"`
	} `json:"providers,omitempty"`

	// Total Total number of providers
	Total *int `json:"total,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = Provider

// ApplyProviderJSONRequestBody defines body for ApplyProvider for application/json ContentType.
type ApplyProviderJSONRequestBody = Provider

// RegisterProviderJSONRequestBody defines body for RegisterProvider for application/json ContentType.
type RegisterProviderJSONRequestBody = RegistrationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get service catalog
	// (GET /admin/catalog)
	GetCatalog(w http.ResponseWriter, r *http.Request)
	// Get service registry
	// (GET /admin/registry)
	GetRegistry(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	ListHealth(w http.ResponseWriter, r *http.Request)
	// List all providers
	// (GET /providers)
	ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams)
	// Create a Service Provider
	// (POST /providers)
	CreateProvider(w http.ResponseWriter, r *http.Request)
	// Delete a service Provider
	// (DELETE /providers/{providerId})
	DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// Get a provider
	// (GET /providers/{providerId})
	GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// Update a Service Provider
	// (PUT /providers/{providerId})
	ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// List registered providers
	// (GET /resource/{resourceKind}/provider)
	ListRegisteredProviders(w http.ResponseWriter, r *http.Request, resourceKind string)
	// Register a service provider
	// (POST /resource/{resourceKind}/provider)
	RegisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string)
	// Unregister a provider
	// (DELETE /resource/{resourceKind}/provider/{providerId})
	UnregisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string)
	// Get registered provider
	// (GET /resource/{resourceKind}/provider/{providerId})
	GetRegisteredProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get service catalog
// (GET /admin/catalog)
func (_ Unimplemented) GetCatalog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get service registry
// (GET /admin/registry)
func (_ Unimplemented) GetRegistry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) ListHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all providers
// (GET /providers)
func (_ Unimplemented) ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a Service Provider
// (POST /providers)
func (_ Unimplemented) CreateProvider(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service Provider
// (DELETE /providers/{providerId})
func (_ Unimplemented) DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a provider
// (GET /providers/{providerId})
func (_ Unimplemented) GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a Service Provider
// (PUT /providers/{providerId})
func (_ Unimplemented) ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List registered providers
// (GET /resource/{resourceKind}/provider)
func (_ Unimplemented) ListRegisteredProviders(w http.ResponseWriter, r *http.Request, resourceKind string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a service provider
// (POST /resource/{resourceKind}/provider)
func (_ Unimplemented) RegisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unregister a provider
// (DELETE /resource/{resourceKind}/provider/{providerId})
func (_ Unimplemented) UnregisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get registered provider
// (GET /resource/{resourceKind}/provider/{providerId})
func (_ Unimplemented) GetRegisteredProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCatalog operation middleware
func (siw *ServerInterfaceWrapper) GetCatalog(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRegistry operation middleware
func (siw *ServerInterfaceWrapper) GetRegistry(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRegistry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListHealth operation middleware
func (siw *ServerInterfaceWrapper) ListHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProvidersParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteProvider operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ApplyProvider operation middleware
func (siw *ServerInterfaceWrapper) ApplyProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListRegisteredProviders operation middleware
func (siw *ServerInterfaceWrapper) ListRegisteredProviders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceKind" -------------
	var resourceKind string

	err = runtime.BindStyledParameterWithOptions("simple", "resourceKind", chi.URLParam(r, "resourceKind"), &resourceKind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceKind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRegisteredProviders(w, r, resourceKind)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RegisterProvider operation middleware
func (siw *ServerInterfaceWrapper) RegisterProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceKind" -------------
	var resourceKind string

	err = runtime.BindStyledParameterWithOptions("simple", "resourceKind", chi.URLParam(r, "resourceKind"), &resourceKind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceKind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterProvider(w, r, resourceKind)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UnregisterProvider operation middleware
func (siw *ServerInterfaceWrapper) UnregisterProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceKind" -------------
	var resourceKind string

	err = runtime.BindStyledParameterWithOptions("simple", "resourceKind", chi.URLParam(r, "resourceKind"), &resourceKind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceKind", Err: err})
		return
	}

	// ------------- Path parameter "providerId" -------------
	var providerId string

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnregisterProvider(w, r, resourceKind, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRegisteredProvider operation middleware
func (siw *ServerInterfaceWrapper) GetRegisteredProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "resourceKind" -------------
	var resourceKind string

	err = runtime.BindStyledParameterWithOptions("simple", "resourceKind", chi.URLParam(r, "resourceKind"), &resourceKind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceKind", Err: err})
		return
	}

	// ------------- Path parameter "providerId" -------------
	var providerId string

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRegisteredProvider(w, r, resourceKind, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/catalog", wrapper.GetCatalog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/registry", wrapper.GetRegistry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.ListHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers", wrapper.ListProviders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/providers", wrapper.CreateProvider)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/providers/{providerId}", wrapper.DeleteProvider)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers/{providerId}", wrapper.GetProvider)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/providers/{providerId}", wrapper.ApplyProvider)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/resource/{resourceKind}/provider", wrapper.ListRegisteredProviders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/resource/{resourceKind}/provider", wrapper.RegisterProvider)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/resource/{resourceKind}/provider/{providerId}", wrapper.UnregisterProvider)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/resource/{resourceKind}/provider/{providerId}", wrapper.GetRegisteredProvider)
	})

	return r
}

type GetCatalogRequestObject struct {
}

type GetCatalogResponseObject interface {
	VisitGetCatalogResponse(w http.ResponseWriter) error
}

type GetCatalog200JSONResponse CatalogView

func (response GetCatalog200JSONResponse) VisitGetCatalogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalog500JSONResponse Error500

func (response GetCatalog500JSONResponse) VisitGetCatalogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRegistryRequestObject struct {
}

type GetRegistryResponseObject interface {
	VisitGetRegistryResponse(w http.ResponseWriter) error
}

type GetRegistry200JSONResponse RegistryView

func (response GetRegistry200JSONResponse) VisitGetRegistryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRegistry500JSONResponse Error500

func (response GetRegistry500JSONResponse) VisitGetRegistryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListHealthRequestObject struct {
}

type ListHealthResponseObject interface {
	VisitListHealthResponse(w http.ResponseWriter) error
}

type ListHealth200Response struct {
}

func (response ListHealth200Response) VisitListHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ListProvidersRequestObject struct {
	Params ListProvidersParams
}

type ListProvidersResponseObject interface {
	VisitListProvidersResponse(w http.ResponseWriter) error
}

type ListProviders200JSONResponse ProviderList

func (response ListProviders200JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProviders400JSONResponse Error400

func (response ListProviders400JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListProviders500JSONResponse Error500

func (response ListProviders500JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateProviderRequestObject struct {
	Body *CreateProviderJSONRequestBody
}

type CreateProviderResponseObject interface {
	VisitCreateProviderResponse(w http.ResponseWriter) error
}

type CreateProvider201JSONResponse Provider

func (response CreateProvider201JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider400JSONResponse Error400

func (response CreateProvider400JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider500JSONResponse Error500

func (response CreateProvider500JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
}

type DeleteProviderResponseObject interface {
	VisitDeleteProviderResponse(w http.ResponseWriter) error
}

type DeleteProvider204JSONResponse Provider

func (response DeleteProvider204JSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProvider400JSONResponse Error400

func (response DeleteProvider400JSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProvider404JSONResponse Error404

func (response DeleteProvider404JSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProvider500JSONResponse Error500

func (response DeleteProvider500JSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
}

type GetProviderResponseObject interface {
	VisitGetProviderResponse(w http.ResponseWriter) error
}

type GetProvider200JSONResponse Provider

func (response GetProvider200JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProvider400JSONResponse Error400

func (response GetProvider400JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetProvider404JSONResponse Error404

func (response GetProvider404JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProvider500JSONResponse Error500

func (response GetProvider500JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
	Body       *ApplyProviderJSONRequestBody
}

type ApplyProviderResponseObject interface {
	VisitApplyProviderResponse(w http.ResponseWriter) error
}

type ApplyProvider201JSONResponse Provider

func (response ApplyProvider201JSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider400JSONResponse Error400

func (response ApplyProvider400JSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider404JSONResponse Error404

func (response ApplyProvider404JSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider500JSONResponse Error500

func (response ApplyProvider500JSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListRegisteredProvidersRequestObject struct {
	ResourceKind string `json:"resourceKind"`
}

type ListRegisteredProvidersResponseObject interface {
	VisitListRegisteredProvidersResponse(w http.ResponseWriter) error
}

type ListRegisteredProviders200JSONResponse []RegisteredProvider

func (response ListRegisteredProviders200JSONResponse) VisitListRegisteredProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRegisteredProviders400JSONResponse Error400

func (response ListRegisteredProviders400JSONResponse) VisitListRegisteredProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListRegisteredProviders500JSONResponse Error500

func (response ListRegisteredProviders500JSONResponse) VisitListRegisteredProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterProviderRequestObject struct {
	ResourceKind string `json:"resourceKind"`
	Body         *RegisterProviderJSONRequestBody
}

type RegisterProviderResponseObject interface {
	VisitRegisterProviderResponse(w http.ResponseWriter) error
}

type RegisterProvider200JSONResponse RegistrationResponse

func (response RegisterProvider200JSONResponse) VisitRegisterProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterProvider400JSONResponse Error400

func (response RegisterProvider400JSONResponse) VisitRegisterProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterProvider500JSONResponse Error500

func (response RegisterProvider500JSONResponse) VisitRegisterProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UnregisterProviderRequestObject struct {
	ResourceKind string `json:"resourceKind"`
	ProviderId   string `json:"providerId"`
}

type UnregisterProviderResponseObject interface {
	VisitUnregisterProviderResponse(w http.ResponseWriter) error
}

type UnregisterProvider204Response struct {
}

func (response UnregisterProvider204Response) VisitUnregisterProviderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnregisterProvider404JSONResponse Error404

func (response UnregisterProvider404JSONResponse) VisitUnregisterProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UnregisterProvider500JSONResponse Error500

func (response UnregisterProvider500JSONResponse) VisitUnregisterProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRegisteredProviderRequestObject struct {
	ResourceKind string `json:"resourceKind"`
	ProviderId   string `json:"providerId"`
}

type GetRegisteredProviderResponseObject interface {
	VisitGetRegisteredProviderResponse(w http.ResponseWriter) error
}

type GetRegisteredProvider200JSONResponse RegisteredProvider

func (response GetRegisteredProvider200JSONResponse) VisitGetRegisteredProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRegisteredProvider404JSONResponse Error404

func (response GetRegisteredProvider404JSONResponse) VisitGetRegisteredProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRegisteredProvider500JSONResponse Error500

func (response GetRegisteredProvider500JSONResponse) VisitGetRegisteredProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get service catalog
	// (GET /admin/catalog)
	GetCatalog(ctx context.Context, request GetCatalogRequestObject) (GetCatalogResponseObject, error)
	// Get service registry
	// (GET /admin/registry)
	GetRegistry(ctx context.Context, request GetRegistryRequestObject) (GetRegistryResponseObject, error)
	// Health check
	// (GET /health)
	ListHealth(ctx context.Context, request ListHealthRequestObject) (ListHealthResponseObject, error)
	// List all providers
	// (GET /providers)
	ListProviders(ctx context.Context, request ListProvidersRequestObject) (ListProvidersResponseObject, error)
	// Create a Service Provider
	// (POST /providers)
	CreateProvider(ctx context.Context, request CreateProviderRequestObject) (CreateProviderResponseObject, error)
	// Delete a service Provider
	// (DELETE /providers/{providerId})
	DeleteProvider(ctx context.Context, request DeleteProviderRequestObject) (DeleteProviderResponseObject, error)
	// Get a provider
	// (GET /providers/{providerId})
	GetProvider(ctx context.Context, request GetProviderRequestObject) (GetProviderResponseObject, error)
	// Update a Service Provider
	// (PUT /providers/{providerId})
	ApplyProvider(ctx context.Context, request ApplyProviderRequestObject) (ApplyProviderResponseObject, error)
	// List registered providers
	// (GET /resource/{resourceKind}/provider)
	ListRegisteredProviders(ctx context.Context, request ListRegisteredProvidersRequestObject) (ListRegisteredProvidersResponseObject, error)
	// Register a service provider
	// (POST /resource/{resourceKind}/provider)
	RegisterProvider(ctx context.Context, request RegisterProviderRequestObject) (RegisterProviderResponseObject, error)
	// Unregister a provider
	// (DELETE /resource/{resourceKind}/provider/{providerId})
	UnregisterProvider(ctx context.Context, request UnregisterProviderRequestObject) (UnregisterProviderResponseObject, error)
	// Get registered provider
	// (GET /resource/{resourceKind}/provider/{providerId})
	GetRegisteredProvider(ctx context.Context, request GetRegisteredProviderRequestObject) (GetRegisteredProviderResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCatalog operation middleware
func (sh *strictHandler) GetCatalog(w http.ResponseWriter, r *http.Request) {
	var request GetCatalogRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCatalog(ctx, request.(GetCatalogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCatalog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCatalogResponseObject); ok {
		if err := validResponse.VisitGetCatalogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRegistry operation middleware
func (sh *strictHandler) GetRegistry(w http.ResponseWriter, r *http.Request) {
	var request GetRegistryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRegistry(ctx, request.(GetRegistryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRegistry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRegistryResponseObject); ok {
		if err := validResponse.VisitGetRegistryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListHealth operation middleware
func (sh *strictHandler) ListHealth(w http.ResponseWriter, r *http.Request) {
	var request ListHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHealth(ctx, request.(ListHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHealthResponseObject); ok {
		if err := validResponse.VisitListHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProviders operation middleware
func (sh *strictHandler) ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams) {
	var request ListProvidersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProviders(ctx, request.(ListProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProvidersResponseObject); ok {
		if err := validResponse.VisitListProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProvider operation middleware
func (sh *strictHandler) CreateProvider(w http.ResponseWriter, r *http.Request) {
	var request CreateProviderRequestObject

	var body CreateProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProvider(ctx, request.(CreateProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProviderResponseObject); ok {
		if err := validResponse.VisitCreateProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProvider operation middleware
func (sh *strictHandler) DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request DeleteProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProvider(ctx, request.(DeleteProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProviderResponseObject); ok {
		if err := validResponse.VisitDeleteProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvider operation middleware
func (sh *strictHandler) GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request GetProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvider(ctx, request.(GetProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProviderResponseObject); ok {
		if err := validResponse.VisitGetProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyProvider operation middleware
func (sh *strictHandler) ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request ApplyProviderRequestObject

	request.ProviderId = providerId

	var body ApplyProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyProvider(ctx, request.(ApplyProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyProviderResponseObject); ok {
		if err := validResponse.VisitApplyProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRegisteredProviders operation middleware
func (sh *strictHandler) ListRegisteredProviders(w http.ResponseWriter, r *http.Request, resourceKind string) {
	var request ListRegisteredProvidersRequestObject

	request.ResourceKind = resourceKind

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRegisteredProviders(ctx, request.(ListRegisteredProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRegisteredProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRegisteredProvidersResponseObject); ok {
		if err := validResponse.VisitListRegisteredProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterProvider operation middleware
func (sh *strictHandler) RegisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string) {
	var request RegisterProviderRequestObject

	request.ResourceKind = resourceKind

	var body RegisterProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterProvider(ctx, request.(RegisterProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterProviderResponseObject); ok {
		if err := validResponse.VisitRegisterProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnregisterProvider operation middleware
func (sh *strictHandler) UnregisterProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string) {
	var request UnregisterProviderRequestObject

	request.ResourceKind = resourceKind
	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnregisterProvider(ctx, request.(UnregisterProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnregisterProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnregisterProviderResponseObject); ok {
		if err := validResponse.VisitUnregisterProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRegisteredProvider operation middleware
func (sh *strictHandler) GetRegisteredProvider(w http.ResponseWriter, r *http.Request, resourceKind string, providerId string) {
	var request GetRegisteredProviderRequestObject

	request.ResourceKind = resourceKind
	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRegisteredProvider(ctx, request.(GetRegisteredProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRegisteredProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRegisteredProviderResponseObject); ok {
		if err := validResponse.VisitGetRegisteredProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
