// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// VM defines model for VM.
type VM struct {
	// Id ID of the VM
	Id *string `json:"id,omitempty"`

	// Name Name of the VM
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the VM
	Namespace *string `json:"namespace,omitempty"`
}

// VMProvider defines model for VMProvider.
type VMProvider struct {
	// Description Summary of Service Provider
	Description string `json:"description"`

	// Id Unique identifier for the Service Provider
	Id string `json:"id"`

	// Name Name of the Service Provider
	Name string `json:"name"`

	// Type Type of the Service Provider
	Type string `json:"type"`
}

// VMProviderList defines model for VMProviderList.
type VMProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string       `json:"next_page_token,omitempty"`
	Providers     *[]VMProvider `json:"providers,omitempty"`
}

// VMRequest defines model for VMRequest.
type VMRequest struct {
	// Cpu CPU for the VM
	Cpu *int `json:"cpu,omitempty"`

	// Id ID of the VM
	Id *string `json:"id,omitempty"`

	// Name Name of the VM
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the VM
	Namespace *string `json:"namespace,omitempty"`

	// OsImage Base image of the OS
	OsImage *string `json:"osImage,omitempty"`

	// Ram Ram for the CPU
	Ram *int `json:"ram,omitempty"`
}

// DeleteVMParams defines parameters for DeleteVM.
type DeleteVMParams struct {
	AppID *openapi_types.UUID `form:"appID,omitempty" json:"appID,omitempty"`
}

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VMRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	ListHealth(w http.ResponseWriter, r *http.Request)
	// Delete an application
	// (DELETE /vm/provider/{provider-id}/application)
	DeleteVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID, params DeleteVMParams)
	// Create a VM
	// (POST /vm/provider/{provider-id}/application)
	CreateVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// Get all providers
	// (GET /vm/providers)
	ListVMProviders(w http.ResponseWriter, r *http.Request)
	// Get a provider
	// (GET /vm/providers/{provider-id})
	GetVMProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) ListHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an application
// (DELETE /vm/provider/{provider-id}/application)
func (_ Unimplemented) DeleteVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID, params DeleteVMParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a VM
// (POST /vm/provider/{provider-id}/application)
func (_ Unimplemented) CreateVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all providers
// (GET /vm/providers)
func (_ Unimplemented) ListVMProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a provider
// (GET /vm/providers/{provider-id})
func (_ Unimplemented) GetVMProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListHealth operation middleware
func (siw *ServerInterfaceWrapper) ListHealth(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteVM operation middleware
func (siw *ServerInterfaceWrapper) DeleteVM(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "provider-id" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "provider-id", chi.URLParam(r, "provider-id"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider-id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteVMParams

	// ------------- Optional query parameter "appID" -------------

	err = runtime.BindQueryParameter("form", true, false, "appID", r.URL.Query(), &params.AppID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "appID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVM(w, r, providerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateVM operation middleware
func (siw *ServerInterfaceWrapper) CreateVM(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "provider-id" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "provider-id", chi.URLParam(r, "provider-id"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVM(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListVMProviders operation middleware
func (siw *ServerInterfaceWrapper) ListVMProviders(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVMProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVMProvider operation middleware
func (siw *ServerInterfaceWrapper) GetVMProvider(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "provider-id" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "provider-id", chi.URLParam(r, "provider-id"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVMProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.ListHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vm/provider/{provider-id}/application", wrapper.DeleteVM)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vm/provider/{provider-id}/application", wrapper.CreateVM)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vm/providers", wrapper.ListVMProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vm/providers/{provider-id}", wrapper.GetVMProvider)
	})

	return r
}

type ListHealthRequestObject struct {
}

type ListHealthResponseObject interface {
	VisitListHealthResponse(w http.ResponseWriter) error
}

type ListHealth200Response struct {
}

func (response ListHealth200Response) VisitListHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DeleteVMRequestObject struct {
	ProviderId openapi_types.UUID `json:"provider-id"`
	Params     DeleteVMParams
}

type DeleteVMResponseObject interface {
	VisitDeleteVMResponse(w http.ResponseWriter) error
}

type DeleteVM204JSONResponse VM

func (response DeleteVM204JSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVM400JSONResponse Error

func (response DeleteVM400JSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVM500JSONResponse Error

func (response DeleteVM500JSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateVMRequestObject struct {
	ProviderId openapi_types.UUID `json:"provider-id"`
	Body       *CreateVMJSONRequestBody
}

type CreateVMResponseObject interface {
	VisitCreateVMResponse(w http.ResponseWriter) error
}

type CreateVM201JSONResponse VM

func (response CreateVM201JSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateVM400JSONResponse Error

func (response CreateVM400JSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateVM500JSONResponse Error

func (response CreateVM500JSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListVMProvidersRequestObject struct {
}

type ListVMProvidersResponseObject interface {
	VisitListVMProvidersResponse(w http.ResponseWriter) error
}

type ListVMProviders200JSONResponse VMProviderList

func (response ListVMProviders200JSONResponse) VisitListVMProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListVMProviders400JSONResponse Error

func (response ListVMProviders400JSONResponse) VisitListVMProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListVMProviders500JSONResponse Error

func (response ListVMProviders500JSONResponse) VisitListVMProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetVMProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"provider-id"`
}

type GetVMProviderResponseObject interface {
	VisitGetVMProviderResponse(w http.ResponseWriter) error
}

type GetVMProvider200JSONResponse VMProvider

func (response GetVMProvider200JSONResponse) VisitGetVMProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVMProvider400JSONResponse Error

func (response GetVMProvider400JSONResponse) VisitGetVMProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetVMProvider500JSONResponse Error

func (response GetVMProvider500JSONResponse) VisitGetVMProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	ListHealth(ctx context.Context, request ListHealthRequestObject) (ListHealthResponseObject, error)
	// Delete an application
	// (DELETE /vm/provider/{provider-id}/application)
	DeleteVM(ctx context.Context, request DeleteVMRequestObject) (DeleteVMResponseObject, error)
	// Create a VM
	// (POST /vm/provider/{provider-id}/application)
	CreateVM(ctx context.Context, request CreateVMRequestObject) (CreateVMResponseObject, error)
	// Get all providers
	// (GET /vm/providers)
	ListVMProviders(ctx context.Context, request ListVMProvidersRequestObject) (ListVMProvidersResponseObject, error)
	// Get a provider
	// (GET /vm/providers/{provider-id})
	GetVMProvider(ctx context.Context, request GetVMProviderRequestObject) (GetVMProviderResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListHealth operation middleware
func (sh *strictHandler) ListHealth(w http.ResponseWriter, r *http.Request) {
	var request ListHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHealth(ctx, request.(ListHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHealthResponseObject); ok {
		if err := validResponse.VisitListHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVM operation middleware
func (sh *strictHandler) DeleteVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID, params DeleteVMParams) {
	var request DeleteVMRequestObject

	request.ProviderId = providerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVM(ctx, request.(DeleteVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVMResponseObject); ok {
		if err := validResponse.VisitDeleteVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVM operation middleware
func (sh *strictHandler) CreateVM(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request CreateVMRequestObject

	request.ProviderId = providerId

	var body CreateVMJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVM(ctx, request.(CreateVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVMResponseObject); ok {
		if err := validResponse.VisitCreateVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVMProviders operation middleware
func (sh *strictHandler) ListVMProviders(w http.ResponseWriter, r *http.Request) {
	var request ListVMProvidersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVMProviders(ctx, request.(ListVMProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVMProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVMProvidersResponseObject); ok {
		if err := validResponse.VisitListVMProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVMProvider operation middleware
func (sh *strictHandler) GetVMProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request GetVMProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVMProvider(ctx, request.(GetVMProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVMProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVMProviderResponseObject); ok {
		if err := validResponse.VisitGetVMProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
