// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xae08buRb/KpbvlS7oDkygYaXNfxTYblhIWR6qulVVOTNnEsOM7doeIIvy3Ve255mZ",
	"JLzTVfmPjO3z/B2fh7nDAU8EZ8C0wr07LIgkCWiQ7pfk1zQE2Q/NrxBUIKnQlDPcwyfZGqIhME0jChJ7",
	"mJolQfQYe5iRBMyvkoiHJXxPqYQQ97RMwcMqGENCDHU9EWa30pKyEZ5OPaxAXtMA2pifuSVEmdKEmT+W",
	"CFHSepQM5xOxUA5z8L4yZLQeIsc0X7ReOZCSy26nk3lIgNQU7ErAQ2gKafcju+ZhuCWJiAH3up2OlzOi",
	"TMMIJJ56GMzmJo0+uyYxDRFlItXYa7FUqc2XjMjXYhsfXkKgDflM9u5TZe8+QPZTUDyVASDGNYp4ysKn",
	"KrDzVOPvPND4GiQjMcoQhNy+xyuRx26LEkSQIY1p/rsuyBFVGvGokMMQVohLpAQElMSodtzDVEOiWgBd",
	"iESkJBOrOQsFp0w3eX60f5AY5fcICkgcD0lw5SeEkREkwDTKz6M1GiERpyPKEFVIQsI1rDdN5eEENAmJ",
	"tvFGwpA6LicVa7iobBjPRfNcnebekwHRMOJygtbIjfIQ+TuV4CENUpKIy8RDhCk6jMFDQyLBiBd7KEiV",
	"5kmrAmlKW26kC0a/p9W7CEVcIj2G0n4hRJRBWPuIPWyEIBr3HOEWhtcglWVytwR4GQFrqIxOxcMloUXQ",
	"NFBrwpPBrf4myAi+aX4FrKn+uflsVZagJYVrykZWUXMSmZMGvxJUGmtVjUgMk0Px117/l/7lweR4+6Iz",
	"OP/87ujTRffjp74+Pj+8Op5sjQf7F9tH539OBpefbwf7B+8G+7s3x3uHv7ZZK7eslbsIhP9KiHAP/8cv",
	"066fXe1+EZWN+JguMNQpjKjSkujMNXWDzY+rgzxi9JhoRI0VTCSpOlbyUDI3UEQCeJ1Iyu6XhVG2GIJz",
	"sNeGuCyH97NSouVOlEA0hLvWiEWUhETDhqZJq0lcZC6NqHq19SDbNQqTpcxSET5MjRmTWqqzNUxFg3vY",
	"ds9asmnhUE5O05Zo7kfIql/iUY15GofIFiNEAxqm2qZ15yOLXZml+1KhIecxEFaF3JwcM04TwjYiSYGF",
	"8QRVUfQ4v7Xngg2bLyMaoJKSi8MkVbrUjoyIqXAL9f+n0OHZxwE6c5XiM8BixsePc+95FpIzTq2qfvfo",
	"GJl7SdSbk4fpWeanplpmL2URdzUd0yQwETOd9eX+3jHKy/8ix++e9LGHYxoAU1bqrPTfFSQYA9re7GAP",
	"pzLGPTzWWqie79/c3GwSu7zJ5cjPzir/qL93MDg72Nje7GyOdRLbu49qm6vm8C0SNL7eIrEYky1ziAtg",
	"RFDcw+82O1YA05ZYF/ljILEemz9H0JIjfrfLKBhDcGWT6gKljettEjL+sJWiO20bHSW4Ucpw2Ha180wA",
	"/uG6rTRJiJzMcLZLfi2fZtI2eZ4Uu9rZGoeCS4dEiJgG9rh/qRxIyxbsPona1igWL3Vtdk3WNnVGKfPU",
	"w91nlKBoAVu4vychMlgHZWN057nZ7rSzrTUpILMepe5V2z9IW7CAhLBuH8FVi1NPs90nZaGaKfeeh5Nn",
	"d6nTrN6ZTxtQ2nohvnM6h9JibziyOMpBgQhicFM2MfWLwr8rU8TU3Tkx6Jb0v2+/I1L0tZWuqI5Gt7OC",
	"xWol8OXuCeOvZfnrawOE3VcB4YCjnMfqsNd9RmWLCdS/C/INjFa7xdbk/QF0C6TRkCgIEWcodZOC/n4D",
	"5R9A/xgQ77wKxE3x8Qbt1UHbAVVU8CzSFjxfCNcTMQS3VGnKRsvv610h4snKsPxzlClv4bPa8MnjotGY",
	"uXIoi5ENO6tf2DtVuvknt0/3GnhWxwfNmef8tqr2/PATgG9QvFv9iP3cjDcamPPvalOl6VwMfoAqBJu3",
	"dZsm5Ra/Prt60WqiBtym6aqvwm/wXG1hUUUnKl4qlqPUL0W8B1iLgexKIVu30G/ZM2nPTsUrc2NElKmi",
	"snlnc/7p1dg48v9fxq1Kfy2UJNLrbqIdxBSYRgFhKFWANC/H2xVjtU5h53OIuKx7tkLqLeBWGnCzYHNU",
	"hvk7bOXBwz1MU1XzZC0071Wv5I9Lr1qzFK+Fj6lbaCHxgnRa2TRvNuqe02YlepnOo/0l75XbkIbxm8Z2",
	"goUzlnVfs3HhrIXrkCsSQWNo2DYKbBr/URmg/fbfnjOqpJwhEgQgNIRojagJC9bbx0VrGRTsP8Jckxjx",
	"aL0yFKIVFC/Jci+jYec1oXHWovXblV2bEtKa+dwx52X3aOnj6dfpPwEAAP//2aGIUTQqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
