// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa23IbN9J+FRT+VMX+w7MUOeZNSpacmI4ka2UpqaytVYEzPSRsDDAGMBJpLd99C4c5",
	"cUCJTnllbe3ekRygu9Ho/vrrHt7iSKSZ4MC1wuNbrKI5pMR+fCmlkOZDDCqSNNNUcDzGZ78coGc/DZ4h",
	"s5FRwjUCsxJJUJngCnAHZ1JkIDUF5fZrQllb0qs8JbwrgcRkygDBImOEE/MQqQwimtAIaYH0nCokoiiX",
	"EnhkxMOCpBkDPMbnc0Dfc5LC9yihwGJEFZLwKacSYjTNNbohCnGhUSbFNY0hxh2sl5nZqrSkfIZXHUy5",
	"0sRIbll4cTZBEhKwilEipDOmtM4dfINtfftU9YejHdj9ce9ZF356Pu0OR/FOl+z+uNfdHe3tDXeHz3YH",
	"gwHu4ETIlGg8xrmk3VJpyF6lic5VwJ/n56fIPUSRiBvW7A4GpSTKNcxAGlGaahY499u5kBrNm/ej8jQl",
	"colEgvQcjEenDNLGkSf8mjAaownPch0y3f1wt5tpDFzTZEn5zCpyTrY767rmWmdq3O/HUdrzv/YikRZe",
	"p86ULvWmbOveVQcXAYTH77BX6/x0Wa4W0w8QaXOiV0CYngcuw/5eXIeifMZAC26yROQyamdJRkJiDggX",
	"nEaEIfO88H1NSM0hzhJjP4nfcLbEYy1z+JIAqtsckL0Muqvpkg5edAlk3dJEdzQNkivjUG/lZQdnLJeE",
	"lcKNwtJNhenmh5wRWT9eYQHIaxqBT2zZM3FARd8vM4ad+kftg/6SM1ZAgiy9iSRkEhRwbUGodUORBKLh",
	"StM0EMPnNAWlSZqhmznwIkOcAgNCCZVKIwkzqjRIC0RlSMZEQ9eK3eLyYqoyRpZXBvXuxVS/GJnFHr8q",
	"uxo3/Fs+hd+p1Oit8ys6rVa1bAAeZ4JyvcGzxWN0cXZk3CGh6Y/904kBahJFoBSdsnBiq2zYSGyS0f71",
	"kLBsTob963Qtp0Nmuli42irca7DWdo7x53Kby6FxAN04/ZSXsEZBlhcRcHWlc8uykZLFEfCZwY69nQ5O",
	"KS++DjtF4uEx/sc70v086D6/fOI/dC9vB5294ar4/enP321zwBQ0iYkm5pjfSUjwGP9fv6IQfc8f+sWR",
	"jov1qw4OR6x3j41Qfwd3+uVjPoVrKnV3ONoJXbrJWJu/gRs/okobJdUapPIsE1JDXCvvXv16yXnnEQB3",
	"cAwM7Ic8M8lr4IxqSK3KDUUPEynJ0nwPI/1ZgUIW6KtoaRy+iM6tWcX9tcBe2NU1SGXtaFEB+xz558UN",
	"1V3kruy08GSzcBQJixvBeP3OhNwPT+yzf05Bk6c/25/+/7sg4XHarsLs4dzYIJLKJnOHJdaIJAG5ZlP6",
	"JazqzEK29Ly0LI08T01ENADdBUNsoqGOHbUV916HE/EXawwjSqPCiL9WX9boj03ZGt6v3UUrfC6/lA5U",
	"AX1bfLyi8arBD8o1uEEIsnaBClOCcmGdFBgoaHv4lMwoN+5DzENFXXmTDnBY6KuMzOBKi48QSJ1z87OF",
	"FQlaUrguGK3ZicxOo0CCytla1sDydfb3g8ne5MPL5fHoYnBy/ufO0R8Xu2/+mOjj89cfj5fD+cnhxejo",
	"/G/Lkw9/Lk4OX+6cHO7fHB+8fh6K7eoQ49sKqLbB7zZ+rQIkuIX241tM4pgaRxB2WnObC7qmn/bLlago",
	"L4hMRa7XC3LT/yaxBL+ynU7L97+CmEmSzWmE3DrbEYXIiKsF0LyAXHWBKN0dhrxZxPK9Tiwg/YBkJKJ6",
	"eRfMHNgWUlelibBtmMlGYt7BnwUPOGb/mlBGppRRvURmCRISGZdHwDXITYWnWtGdbtEFrDq4dfjNFS/y",
	"SxDlDrNC7FsLTdhVlOWhRNOEoYPTCxQJCQoRd8Ymrxxt6ICt2BRSIZebJLunYbF4eP4i2OlauTwYnE4q",
	"z9OpLVDIrGrE3/AuW5UWksw2ivWPN1g7Clnbvr6VHYskwrY9gmsSGbBcrWfu4cFxi6xZdt9FjbJJeIxS",
	"wskMUhvjSWuX6r3n56Zw297AGGtWqiAd9F2Ul50wcYOIQjEklEOMqC2M77mxDfic8MgpNdEkFGG99ya2",
	"GI2AK+tER0vxfkaiOaBRz9CmXLJaJ3Jzc9Mj9nFPyFnf71X9o8nBy5O3L7uj3qA31ymrTVRwyC24g0ue",
	"VTEjx1k5ySge453eoLfryNLchn3R0I5v8Qz0xiYmmkP00daaTXeCa9R4EluI1K+qkYGb3VmVo8GguHdw",
	"PR7JMkYju7X/QTma6EDuPgh8VbTjrdh585sNPD9VWjuJiVEyawwMzOJ+o5AF/XEGOpdcIVJW8IqAlRSx",
	"FINuqJ4jkXnATSjTYHNi3VmGLpzWqQCRJAVtLXnXaoKtmJqW6XK9qaBm3accpIFuH4ENShXoJFaddUXH",
	"ZEHTPK1BiWcTKDP6DUqEVaVk4aiLop+bOmNISM60x6DUKSi+Ue6/tdGpbVxFfzLHqhyqh8ypsai7zn/5",
	"bwzUBi8MhOvb3E4rkpxVJdqk7u6dNvgh6Q9fZoubvAeMeEFiO94GZUtseVcPpf+CwyKDyPBj8GvqGWzb",
	"a1IbralaHpf05dIQUqH0plYLJCKIw00rWw1Tcd0NIhzBgiptGLXg0HvPG/WGKsNj0kwYn4zf8y6aJG7C",
	"EAtwLwTs9o7X9PYUAddyaTa6Hj+ub7JrPVYokkKfi9KoyWHHTamL/b7/2rQ/pomdPeuGhGZFI5Qp9CQS",
	"PGE00k+9qGr9BoFG172iWsh2YM9bG7XcCW1vCqgsL2VyaHO88nfDgg0JT+NGon/dIVYQNmzSvBDx8qsj",
	"hkuUqms2Lc7qAZAqlKBlwfdRiJ5I6Nbv46nBjdFg+LDW+JxCT0yytcx5UAgtXlG590JW+/OH037gExF1",
	"/cBT1tOaMDtoNhQ2V2CNG40ezrjfjWMcbsAigqwocY+tzNTKROhlRbveNJhjNWiaxCtXg+wsN1CNUnEN",
	"iLTrUCJF6t/D2VBetkD10MrcFlTbbwjWWn6kBSpHzhZP7Qy54k/lifA6Ej0wzDYwbzcwYCtO5I4TI1Xy",
	"Krb8ZmAwObTTa0YhdjbsPpwNpUcMK0lEzuPHmHMuoGvJcHfGdcLN2a+gQ/k0XSKqFcpdGkwOQ63qV8ul",
	"/6gMehjW8Ch6m//l4ra56LIouycBDb1pv2xtt0/r2WgHcVCnJdS/aiJ6jtJcaZQSHc0bQmqbW8m7n2Vs",
	"+VVLoX/p+sgT+b+043gUBb3G7r85fHzTBqPZUphKS7jQ89p08jEiXAFT2/J7/x+BAlLc9L7xhyFsctJv",
	"bf3FYX1aXn9VUf2bpAUxuD3zbEzjQ3uLv6ddrv4VAAD//3QemAF6KwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
