// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

// Defines values for ProviderType.
const (
	Container      ProviderType = "container"
	Database       ProviderType = "database"
	VirtualMachine ProviderType = "virtual_machine"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// Provider defines model for Provider.
type Provider struct {
	// ApiHost Host URL for the provider API
	ApiHost string `json:"apiHost"`

	// Description Summary of Service Provider
	Description string `json:"description"`

	// Endpoint Endpoint of the Service Provider
	Endpoint string `json:"endpoint"`

	// Id Unique identifier for the Service Provider
	Id string `json:"id"`

	// Name Name of the Service Provider
	Name string `json:"name"`

	// Operations Operations performed on the provider endpoint
	Operations []string `json:"operations"`

	// Type Type of the Service Provider
	Type ProviderType `json:"type"`
}

// ProviderType Type of the Service Provider
type ProviderType string

// ProviderList defines model for ProviderList.
type ProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Providers     *[]Provider `json:"providers,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = Provider

// ApplyProviderJSONRequestBody defines body for ApplyProvider for application/json ContentType.
type ApplyProviderJSONRequestBody = Provider
