// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error400 defines model for Error400.
type Error400 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Invalid input
	Error string `json:"error"`
}

// Error404 defines model for Error404.
type Error404 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Resource not found
	Error string `json:"error"`
}

// Error500 defines model for Error500.
type Error500 struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Error Internal service error
	Error string `json:"error"`
}

// Provider defines model for Provider.
type Provider struct {
	// Capabilities List of service types or special capabilities
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Endpoint Optional provider callback/management endpoint (if plugin is remote)
	Endpoint string                  `json:"endpoint"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`

	// Type Provider category (aws, azure, terraform, ansible, baremetal, custom)
	Type string `json:"type"`

	// Uuid Unique identifier for the provider defined the provider
	Uuid    openapi_types.UUID `json:"uuid"`
	Version string             `json:"version"`
}

// ProviderList defines model for ProviderList.
type ProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Providers     *[]Provider `json:"providers,omitempty"`
}

// ProviderRegistration defines model for ProviderRegistration.
type ProviderRegistration struct {
	// Endpoint Endpoint that implements the provider plugin interface
	Endpoint string                  `json:"endpoint"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`
	Service  *string                 `json:"service,omitempty"`
	Type     string                  `json:"type"`
}

// ServiceInstance defines model for ServiceInstance.
type ServiceInstance struct {
	CreatedAt     *time.Time             `json:"createdAt,omitempty"`
	Id            openapi_types.UUID     `json:"id"`
	Parameters    map[string]interface{} `json:"parameters"`
	ServiceTypeId openapi_types.UUID     `json:"serviceTypeId"`
	UpdatedAt     *time.Time             `json:"updatedAt,omitempty"`
}

// ServiceInstanceCreate defines model for ServiceInstanceCreate.
type ServiceInstanceCreate struct {
	// DryRun If true, provider should validate but not create the resource
	DryRun *bool `json:"dryRun,omitempty"`

	// Name Optional human-friendly name
	Name *string `json:"name,omitempty"`

	// Parameters Provider-specific parameters that must validate against provider's JSON Schema
	Parameters    map[string]interface{} `json:"parameters"`
	ServiceTypeId openapi_types.UUID     `json:"serviceTypeId"`
}

// ServiceType defines model for ServiceType.
type ServiceType struct {
	Description *string             `json:"description,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Name        string              `json:"name"`
	ProviderId  *openapi_types.UUID `json:"providerId,omitempty"`
}

// ProviderId defines model for providerId.
type ProviderId = string

// ServiceId defines model for serviceId.
type ServiceId = string

// ServiceTypeId defines model for serviceTypeId.
type ServiceTypeId = string

// RegisterProviderJSONRequestBody defines body for RegisterProvider for application/json ContentType.
type RegisterProviderJSONRequestBody = Provider

// ApplyProviderJSONRequestBody defines body for ApplyProvider for application/json ContentType.
type ApplyProviderJSONRequestBody = Provider

// CreateServiceInstanceJSONRequestBody defines body for CreateServiceInstance for application/json ContentType.
type CreateServiceInstanceJSONRequestBody = ServiceInstanceCreate
