// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa23LbONJ+lS7+UzUz9etsjTPRzZZHchJmbcfrQ1LZyOtAZFNCDAIMAOowLr/7FgCS",
	"IiVKcTIbby72ziQBdKMPX3/d8r0XiDgRHLlW3uDeS4gkMWqU9snnShMeoB+eEz0zb0JUgaSJpoJ7A++a",
	"088pAg2RaxpRlCAi0DMEmm30Gh4uSZww9AZet3eA/d8OnzXx9+eTZrcXHjRJ/7fDZr93eNjtd5/1O52O",
	"1/CoOTkx8hoeJ7HZSQs9vIYn8XNKJYbeQMsUG54KZhgTo1xMlifIp0bTw4OGF1OeP3Yb5kSN0pz9rw+k",
	"+Wen+fzml+yP5s19p3HYfcjf//q3n7yGp1eJka20pHzqPTw85KKsaY6lFHLbIhcvhvDs984zMGZllHAN",
	"aFaCRJUIroxFEikSlJqicvs1oWz7pFdpTHhTIgnJhCHgMmGEE/MRVIIBjWgAWoCeUQUiCFIpcdPgVzOE",
	"n40Jf4aIIguBKsitB5NUw4Io4EJDIsWchhhu37pR2L7G+xc+SIzQCoZISKdMoZ27+A7d2varaj8yKCIh",
	"Y6K9gZdK2iyE1umrNNGpqrHn1dU5uI8QiLCiTb/TKU6iXOMUpTlKU81q7n05E1LDrOoflcYxkas8ARIp",
	"JgzjypV9PieMhuDzJNV1qrsX+82c5dqK8qkV5Ixsd5ZlzbRO1KDdDoO4lb1tBSLOrU6dKk2aqfJY8z6U",
	"0++Dl4l1dropVovJJwy0udErJKwOONz73B2K8ilDLbjJEpHKYDtLklr8GRIuOA0IA/M9t33pkJJBnCZG",
	"fxK+4WyVw8fjA6isc83Zq1pzVU3S8JZNgkmzUNFdzQCTMgbNtLxpeAlLJWHF4UZgYaYC+SifpozI8vVy",
	"DVDOaYBZYsuWiQMq2tkyo9ilW3G1StDfmeIvUsYgO8sGWYHshZVBYiJRIdcWnLY8F0gkGm81jWvOv6Ix",
	"Kk3iBBYz5JXSYcEpolJpcEeE5TgNicamPfMRHg2R4TerEBN5h6GFN3uOu+NfUIQKfrsrxkbZgjwznNQI",
	"pUHsfLdqwdHEGNx+JoGmcxzzXGnVgsvhq+PR9cnxCCgPaUA0quq9qILPKabZtQKGhKdJa8xfHPnbu7LP",
	"MCMKcBkghhhCTJY0TmOQqCVF1Rrz8+OzkX/28vb84s1bf3R8sUf2glBt8MsIp1qNeR6mpqBNMBAxQpZT",
	"MMFIyLUStoIZkWFrbPyAPI1N4hRX9hqeu4XX8DZVMnn1RR/R8DE8x1U7hCyLwKQR+H+B9fxnucsXb1mP",
	"pxd5Tls4XV+3cqEMDprmzGbu1sfW8S8rloXCraN+mxqekRhLNdYurWh3l05wTqVudnsHtfQgwcAcS8KQ",
	"mjMJOy/BlVNqo9xnLs55jeNgkWBMLEwUC15opNIkEVJjWMHMMc94I/zy9vQywaABQ8E1oRylexwRTSZE",
	"oXsSEoYsVdp9/dUF+lZp3QUhlw459hHxi+Oj0fvHOCNNwm/HbkaUBnfCt0L3Bt2oxkbmy5uvrbG18ava",
	"9/mftzR8qFTg+g1epf7WrvliOa7ftaM6n1Clt71wTqaUGxMDo0obt5c1rJZijkt9m5Ap3mpxh7zGpea1",
	"xTYHsvOcZZqdYHYaARJVynSVAuHqdfLPoX/ofzpenfauO2dX7w9O3l3337zz9enV67vTVXd2NrrunVz9",
	"Y3X26f3ybHR8cDY6WpwOXz+vS9NcxuDeoxpj+8dPEiNv4P1fe92ytrPMatexmTX7IlKSVQ0ds00d5ZGw",
	"RMXkZGBM/LAJAaPhKVyeQwGPp4STKcamBB+d+9CEoWEoBhYIN7Wx+CqiokJU2JMpmFemWTLbqbGhWa52",
	"lxSImFgAUYYNUI4hUJtxY25UQz4za6xE43GhCHOowWiApuk0znet9FFCghlCr2XQOJWs1CssFosWsZ9b",
	"Qk7b2V7VPvGHx2eXx81eq9Oa6ZiVWqMCHM+zyP7l8vzXXXbyGt4cpXImnXcJS2akaw4TCXKSUG/gHbQ6",
	"rb7nypP1ec5YB/feFPVOUh7MMLizgbvfVZ4VJq2v/NAbeC9Rv1p3Bq5Ft4J7nU4eFMitYJIkLEP/9icl",
	"bPqsZw/7gvNVzrq3AuvN321UZs3jxn1MXpBppS8wi9s78GiXiS5Qp5IrIAVC1BJ6BQtqeqjEVUWIKNNo",
	"03HTZgaI/DLIlGZGH7Y6CHtMIbJUs+2c53OKcrUe9JQ+r027VRQ2ZfgR2PIBSkS66dh+WLoYkeaaAUvD",
	"InFyEBtzwgSfKhpixqRLOQojjIhZZXhpRJhCl1V1mquZWNxmoivah+4Mb2APKBBoIoShtHXXOc24NU/j",
	"iRupZcpCgtKi8A4dYrJ08K7on1ivRLfTsVzTCMifKM+etmcg28qtS0TiKo/rh2qdua40+9x58x0zb1cZ",
	"rUnFyzQIUKkoZVCEuwGn/l51sjnP/3+dWm54WKPEHyS0EzpU2vWLmdueSv41x2WCgUkfzNaU0cnYDsiu",
	"kYAqAVZBZm4Mpxd1zMXWTAQCHBdr5igiIJXjW2P+JsMktspI+AoIBIwi102iFJ2aguiPxnxOiU3ujzT8",
	"CDYaoQCnFvhRZdjZcAXUyEIJC8oYTJEbzyMQDv7IJXsV+5zSpUZvL/jlioM/silTa7Yd2UOrMPJ9Z9s3",
	"jmij0n+IcPU9089FXXWG/7CFAN3vr8JGCcnjL581PXXm58NhN5G10vtPJ/1MaIhEyrN7P386yUPBI0YD",
	"Dc0iIfwREGY6w5Up1qmyTL7f6z2dUm+NKxyhx2WASV4LfjQ8ziGU78HPelDezSPXjbAfPjjUNqSmjlfG",
	"Yl4R3oJ3M+TwMZ9YfgSqMmaWzy4hIpSl0pGyMZcYCJmxMlIM+exs0rZSjqlZYDItqeWxyhXqFtgGiqox",
	"TxWGEKYGy0DibBXKbEbDxMJyNzIXNIQJE8Gdm9gUPNSZVdVBvZ3F7oH6Ooeul7Q3fjvdZlLWVnussx78",
	"mhtUjePGvUhCxw6NYczFCHf3acH1PpPsZrG5yK9jsNsMrr8dLgXC5vxcFYSLrf5rcOuP7NCO0Rzy+0+p",
	"Q2YRXkbfHw1jXBqU03wXzavtPl+iruDTZAVUK0jdRN0f1XXk3y/nHtMpunTKXmcp1u/0W2P+JO3gE7dD",
	"P2wr9L8MfWyGbqbYxoRnBwEwR9jWx2WWGwW2SULb69HcTbF161eG+hFbES5q+593atKxMr2r25v/Xn3z",
	"8O8AAAD//3ocP5GpJAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
