// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX3PbuBH/KjvszVwy1V9b51z00vFZTsLUdtzYvkwauw5ELiUkIMAAoGWdx9+9swBJ",
	"iRKlONfGzUPfTBLYXSx2f/vble+CSKWZkiitCYZ3QcY0S9Gidk+hNJbJCMP4lNkpvYnRRJpnlisZDIML",
	"yb/kCDxGaXnCUYNKwE4ReLExaAV4y9JMYDAM+ju7OPhl71kbf30+bvd34t02G/yy1x7s7O31B/1ng16v",
	"F7QCTpIz0tcKJEtpJ6/sCFqBxi851xgHQ6tzbAUmmmLKyLiU3R6hnJCle7utIOWyfOy3SKJFTbL/9YG1",
	"/+i1n189Kf5oX931Wnv9+/L907/9FLQCO89It7Gay0lwf39fqnKuOdRa6XWPvH1xAM9+7T0DcqvgTFpA",
	"WgkaTaakIY9kWmWoLUfj91vGxbqkV3nKZFsji9lYIOBtJphk9BFMhhFPeARWgZ1yAyqKcq1x1eHnU4Sf",
	"yYU/Q8JRxMANlN6DcW5hxgxIZSHT6obHGK+fulX5vuH234agMUGnGBKlvTGVdf7gG2zruq+m+8CgSJRO",
	"mQ2GQa55u1LaZK+xzOamwZ/n56fgP0Kk4po1g16vksSlxQlqEmW5FQ3nPpsqbWFavx+TpynT8zIBMq3G",
	"AtPakUN5wwSPIZRZbptM9y+2u7nItTmXE6fIO9ntXNY1tTYzw243jtJO8bYTqbT0OvemtHlhykPde7+c",
	"fh+CQq3301W1Wo0/YWTpRK+QiSbg8O/L6zBcTgRaJSlLVK6j9SzJGvHngEklecQE0PfS90tClhziLSH7",
	"WfxGinkJHw8PoGWbG2TPG91Vd0kruG0zzNqVif5oBEyGHFpYedUKMpFrJirhpLByU4V8XE5ywfTy8UoL",
	"UN/wCIvE1h2KA666xTIy7MyvOJ9nGG5M8Re5EFDIckFWIXvlZdCYaTQorQOntZuLNDKL15anDfLPeYrG",
	"sjSD2RRlrXQ4cEq4Nha8iHg5TmNmse1kPuBGYxRICq83Xe2oWFAGJGFZTFlAQFnuNh3YH9M53WcWWX6D",
	"l7I013Tg9PBkFJ68BC5jHjGLpn4ebuBLjjnGbn8kkMk861zKF/vh0eFoZVfxGabMAN5GiDHGkLJbnuYp",
	"aLSao+lckrdR5imFTqE9aAVeIAXRVz3D44cUdQ/tCEXIAMUMhP9Bif/vFuqvnrIZPN6WAeywY3Hc2oGK",
	"2G+TzHZ5lQ8tWl83rEjPa89zVi08YSkuFRS3tGbd53yMN1zbdn9nt7EWZhiRWBbHnGQycbqUm96oldpW",
	"XHFZxD3hSJQQakYlR8nKIpNnmdIW4xpAXMqCJMGT34/PMoxacKCkZVyi9o8jZtmYGfRPSsOByI31X5/6",
	"mF6rI5sS98zn6zbW+fZwf/T+IZeRZ/GfByrBjAUv4c/i1EptrcdGcZdX31pQGuPXdO/KP695fF8rN40b",
	"glqt2bRke+lp3rWhEh1xY9cv4ZRNuCQPg+DG0q1XJ1orO4sv9GAxdX/8pDEJhsFfuouup1vEa7epIC4K",
	"ONOazelZ4q29ztgEr636jLIhVOi1w0yP0zclVaOdQDvJco0mF7bOI3D+OvvnQbgXfjqcH+9c9E7O3+8e",
	"vbsYvHkX2uPz15+P5/3pyehi5+j8H/OTT+9vT0aHuyej/dnxwevnDyAfroXhMlGuLFNSRuTk+1UMGB0c",
	"w9kpVPh4zCSbYEqVb/80hDYcUD0mXGCSilL1VSVViahxBapU59Qa0HZOh6XlZnNNgUSoGTBDRZhLjIG7",
	"lLuUZBrKKa1xGunOlWHCw4bgEVKLNbwrG8f9jEVThJ0OwXGuxRIzns1mHeY+d5SedIu9pnsUHhyenB22",
	"dzq9ztSmYqkRqNDxtIjtJ2enTzf5KWgFN6iNd+lNn4lsyvokTGUoWcaDYbDb6XUGga9PLjxLfja8CyZo",
	"N1LQaIrRZxdh268qcMq0u6swDobBS7SvFjzYN6RO8U6vVwYFSqeYZZko4L/7ySgX54tOe1sevSo55lpg",
	"vfm7i8qiVVo5DwUwm9RYMC1uxg2z0UVv0eZaGmAVRjTSVwMzTh1D5ssiJFxYdHmz6jOConAZZpYmJB/W",
	"+LITU6lcKtpuqvElRz1fjDWWPi9cu5bFqzrCBFz9AKMS23bs1GVIeTCm6ZiRyOMqcUq0uZRMKDkxPMaC",
	"wC7lKIwwYbQKrIKECYM+q5osN1M1uy5U16yPvYxg6ARUCDRWight03GOC1Ir83TsB0iFsZChdnC5wYaU",
	"3XocNvwPbDaiT319wZrLJy6Lp/WOf924BZZnvvb4DqfxMhclYdt1Xn3HzNtUSBtS8SyPIjQmyQVU4U7g",
	"NNhqTjHV+Ou3meVHZQ1G/MZiN49CY32bVlzbY+m/kHibYUTpg8WaZXQi3wHb1ACbJcCq6MwVkXrVxF1c",
	"zURgIHG2oI4qAVYT37mUbwpMEvOChc+BQSQ4SttmxvAJFcRwdClvOHPJ/ZHHH8FFI1Tg1IEwqY32Wr6A",
	"ki7UMONCwAQl3TwCkxCOfLLXsc8bvdTpbQW/0nAIRy5lGt22IXt4HUa+7yT3yjNtNPY3Fc+/Z/r5qKtP",
	"rO/XEKD//U1YKSFl/JWTlcfO/HIU6uePTvvg8bSfKAuJymVx7uePp/lAyUTwyEK7SohwBExQazinYp0b",
	"13QMdnYez6jf6So8ocfbCLOyFvxoeFxCqNyCn82gvJlHLjrhML73qE2kpolXpuqmprwD76Yo4WM5KPwI",
	"3BTMrBwZQsK4yLUnZZdSY6R0wcpYNeJzQ0HXSnmm5oCJekfHY40v1B1wDRQ3lzI3GEOcE5aBxuk81sWQ",
	"RqiZ427sRvEYxkJFn/3IpuKh3q2mCerdCHQL1Ddd6GJJd+WXwnUm5Xy1xTuLeSudoO4cP2VFFnt2SI6h",
	"gzHpz9OBi20u2cxiS5XfxmDXGdxgPVwqhC35uakIl5j/z+A2HLmpneAl5A8e04bCI3IZfX80jPFpsJzm",
	"m2heY/f5Em0Nn8Zz4NZA7kfq4aipI/9+OfeQTtGnU/G6SLFBb9C5lI/SDj5yO/TDtkL/z9CHZuhqiq1M",
	"eDYQABLhWh+fWX4U2GUZ7y5Gc1fV1rWfGZpHbFW4mPV/VWlIx9r0rmlv+evs1f2/AwAA//9XxVselyMA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
