// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbNhL+Kzu4zjSZE/Vm1Wn05Sa13Ia52PHFTju52OfC5FJCAgIIAFpSPfrvNwBI",
	"SpQo1+1dfPlw30QS2H2wL8/uQnckkbmSAoU1ZHxHFNU0R4vaP8XCWCoSjNMzamfuTYom0UxZJgUZk3eC",
	"fS4QWIrCsoyhBpmBnSGwciPpEFzQXHEkYzIYHuDou8NnEX7//CYaDNODiI6+O4xGw8PDwWjwbNTv90mH",
	"MCdZOX0dImjudrIaB+kQjZ8LpjElY6sL7BCTzDCnDlxOF69RTB3Sw4MOyZmoHgcdJ9GidrL/9YFGv/Wj",
	"51dPyh/R1V2/czhYVe+f/u0b0iF2qZxuYzUTU7JarSpV3jTHWku9a5G3Px7Bs+/7z8CZlTMqLKBbCRqN",
	"ksI4iygtFWrL0IT9ljK+K+llkVMRaaQpveEIuFCcCuo+glGYsIwlYCXYGTMgk6TQGrcNfjFD+NaZ8FvI",
	"GPIUmIHKenBTWJhTA0JaUFreshTT3VN3atu3eP9tDBoz9IohkzqAqdGFg+/B1vNfTe+BQZFJnVNLxqTQ",
	"LKqVtuE1ltrCtNjz4uIMwkdIZNpAM+r3a0lMWJyidqIss7zl3OczqS3Mmv4xRZ5TvawSQGl5wzFvHDkW",
	"t5SzFGKhCtsGPby438xlri2ZmHpFwch+56aumbXKjHu9NMm75dtuIvPK6ixAiVgJ5aHmXW2m3wdSqg12",
	"uqpXy5uPmFh3opdIeRtxhPeVOwwTU45WCpclstDJbpaoVv45okIKllAO7ntl+w0hGwYJSBx+mr4RfFnR",
	"x8MDaBNzi+xlq7maJumQRURRRTXEcDRHTMYZtER51SGKF5ryWrhTWJupZj4mpgWnevN4FQLUtyzBMrF1",
	"18UBk71ymQN2HlZcLBXGe1P8x4JzKGX5IKuZvbYyaFQaDQrryWnHc4lGavHasrxF/gXL0ViaK5jPUDRK",
	"hyenjGljIYhIN+M0pRYjL/MBHmXpQ0pXIDCE0jDgLAPxf1DI/rvl6HdP2Z4ibys3+QxZH7dxoNLDkZMZ",
	"VQ54KDX/PrAyCK9DNd9GeEpz3KBNv7SB7lNxg7dM22gwPGhlfIWJE0vTlDmZlJ9tRGAAtcXgpYurUhXK",
	"aiY5l3NHrFLUiEyhlNQW00YaXIqyFYAnP5+cK0w6cCSFpUygDo8TaukNNRiepIYjXhgbvj7tXgrSwpb7",
	"mOc80OR9vdXb4xeT9w9xRqHSP5+OnBoLQcKfzcatCtKMjdKXV3+UNlvj1/Tuqp/XLF01SLV1A2kw6r4l",
	"9xNs+649fPuaGbvrhDM6ZcJZGDgz1nm9PtEOua6/uAeLuf/xjcaMjMlfeuvevlfGa6+N9tdlimpNl+5Z",
	"4MJeKzrFays/oWgJFffac6ZGqxneVg2J2wlup0Ou0RTcNqslLl+pfx7Fh/HH4+XJ8F3/9OL9wetf3o3e",
	"/BLbk4tXn06Wg9np5N3w9cU/lqcf3y9OJ8cHp5MX85OjV88fUGJ9o85EJn3xcUmZOCOvtjlgcnQC52dQ",
	"8+MJFXSKOQoLL85iiODIVR3HC1SkkK+/yqwuEY2KaLqX4sI1wG47c4d1y83+mgIZl3OgBlLMmMAUmE+5",
	"S+GgoZi5NV6j87k0lAfa4CxBN0iM76rx6IWiyQxh2HV0XGi+0f/N5/Mu9Z+7Uk975V7Tex0fHZ+eH0fD",
	"br87sznfaHdrdjwrY/vJ+dnTfXYiHXKL2gST3g4oVzM6cMKkQkEVI2Ny0O13RyTUJx+eVRcyviNTtHsb",
	"rWSGyScfYfe7inhl2vsqTsmY/IT25brbC2OXVzzs96ugQOEVU6V4Sf+9j0b6OF/Pk/fl0cuqk9oJrDd/",
	"91FZDgRb53EBTKeNXs8tbucNs9dEb9EWWhigNUe0NmkG5sz1xSqURcgYt+jzZttmjoriTZrZuAf4sNMV",
	"ejG1yo2i7Wf3zwXq5Xp43/i8Nu1OFm/rOKELlhc5iCK/CfcKJZeAQu35ZY+6nC4CcRn2GzZ0ppjRglsy",
	"HrhxLw8KqicmyqfdQXAX3Jr8VCDr0Pi2nn7Nofed/+oLhuq+ytMSu+dFkqAxWcGhjg+XzaN74ZTD7l//",
	"GKxwg9IC4gea+msKNL4rqt32WPrfCVwoTFwFxnLNZjo72wHdNxeZjQyv6/+V64JlW7H3RQaBgsD5uteS",
	"GdCG+O6leFMmMV+WbesSKCScobARNYZNXQWJJ5fillFfc35l6a/goxHqbO5CnDVufDqh4jhdqGHOOIcp",
	"Cud5BCognoSa0ySLAHpjNLqXLSrgEE98yrSabU/2sJQ83gXfVWhN0dgfZLr8kukXoq55kbnaYYDBl4fQ",
	"9FTdmFQD92NnfnVDFq6lvPbR42k/lRYyWYjy3M8fT/ORFBlniYWoToh4ApS7WWrp2sLC+C59NBw+Hqif",
	"nStCB4yLBFVVC742Pq4oVNzDn+2kvL/xWo+OcboKrM3RYlsjlsvbhvIdtpz4rfvZss0m6yW9rf9gWjqF",
	"0S6sOpMD7hRMXdj58n+W1vHEX6dwVlHL6DExlBYRm1n+tcVyiJWtcGptJ1rHgp/QNvLgZgnMGijCXWc8",
	"aRuVvmBg9h+7gH0V7ev/o/2h0b4drltj7B7SdiJ8uxqiNNx39KhivfX9w1W9decutf0eoQ4Xs/uvM9kd",
	"ABtXFG17qz9arlb/DgAA//8j/PByYh8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
